# Numpy

In [1]:
x = [1, 3, 5]
y = [7, 4, 0]
x

[1, 3, 5]

In [2]:
y

[7, 4, 0]

In [3]:
import numpy as np

In [4]:
# x = [1, 3, 5]
# y = [7, 4, 0]

x = np.array(x)
y = np.array(y)


In [5]:
 x * y

array([ 7, 12,  0])

In [6]:
2 * x - y

array([-5,  2, 10])

In [7]:
np.array([100, 80, 40])

array([100,  80,  40])

In [8]:
k = np.array([34, 23, 89])
type(k)

numpy.ndarray

In [9]:
np.array([2.3, 5, 6.9, 10], dtype = "int")

array([ 2,  5,  6, 10])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((4,4), dtype = "int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
np.full((3,3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [14]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [16]:
np.random.normal(10, 1, (2,2))  # ort - sapma - size

array([[ 9.56543151, 10.09596022],
       [ 8.94147991,  9.87046781]])

In [17]:
np.random.randint(0, 10, (2,2))

array([[3, 4],
       [8, 9]])

In [18]:
# attr

# ndim: Number of array dimensions, shape: array dimensions, size: Number of elements in the array, dtype: data type

In [19]:
a = np.random.randint(10, size = 10)

In [20]:
a.ndim

1

In [21]:
a.shape

(10,)

In [22]:
a.size

10

In [23]:
a.dtype

dtype('int64')

In [24]:
b = np.random.randint(10, size = (4, 4))
b

array([[4, 6, 2, 7],
       [6, 4, 6, 9],
       [6, 3, 0, 0],
       [5, 0, 6, 2]])

In [25]:
b.shape

(4, 4)

In [26]:
b.size

16

In [27]:
b.ndim

2

In [28]:
b.dtype

dtype('int64')

In [29]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# reshape
np.arange(0,10).reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x.ndim

1

In [33]:
y = x.reshape((3,3))
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
y.ndim

2

In [35]:
# concatenate
x = np.array([3, 4, 2])
y = np.array([2, 6, 8])

In [36]:
np.concatenate([x,y])

array([3, 4, 2, 2, 6, 8])

In [37]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate([x, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate([x, x], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [40]:
# split

In [41]:
x = np.array([23, 45, 56, 67, 45, 12, 34])
x

array([23, 45, 56, 67, 45, 12, 34])

In [42]:
np.split(x, [2, 3, 5])

[array([23, 45]), array([56]), array([67, 45]), array([12, 34])]

In [43]:
a, b, c, d = np.split(x, [2, 3, 5])

In [44]:
a

array([23, 45])

In [45]:
d

array([12, 34])

In [46]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
np.vsplit(x, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [48]:
up, low = np.vsplit(x, [3])
up

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
low

array([[12, 13, 14, 15]])

In [50]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
np.hsplit(x, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [52]:
# sorting

In [53]:
x = np.array([223, 566, 421, 100])
x

array([223, 566, 421, 100])

In [54]:
k = np.sort(x)
k

array([100, 223, 421, 566])

In [55]:
x

array([223, 566, 421, 100])

In [56]:
x.sort()

In [57]:
x

array([100, 223, 421, 566])

In [58]:
v = np.random.randint(0,100, (20,10))
v


array([[23, 93, 25, 47, 45, 76, 85, 59, 57, 89],
       [ 2, 42, 50, 34, 18, 18, 91, 92, 40, 71],
       [ 7, 69, 13, 87, 80, 99, 83, 23, 57, 90],
       [12, 68, 58, 22, 96,  5,  1, 52, 59, 54],
       [34, 25, 79, 37, 78, 46, 58, 94, 93, 44],
       [61, 36, 97, 44, 68, 84, 79, 55,  0, 88],
       [ 2,  2, 20, 26, 79, 98, 36, 30, 92, 87],
       [ 7, 39, 68, 92, 48, 31, 45, 68,  4, 45],
       [90, 75, 69, 30, 53, 43, 87, 36, 50, 73],
       [61, 90, 34, 11, 84, 74, 30, 39,  8, 48],
       [23, 56, 65, 76, 83, 34, 18, 31, 56, 44],
       [73, 43,  6, 89, 36, 42, 59, 18, 72, 91],
       [ 3, 23, 18, 67, 83,  3, 75, 80, 87, 80],
       [42, 42, 55, 21, 94, 28, 81, 30, 91,  8],
       [21, 18, 13, 52, 95, 16, 11, 96, 39, 40],
       [78, 66, 53, 46,  1, 55, 38, 98, 51, 51],
       [93, 68, 45, 54, 97, 68, 71, 96,  5,  2],
       [64, 76, 38, 69, 37, 56, 25, 61, 32, 35],
       [98, 68, 44,  8, 47, 20, 62, 75, 57, 42],
       [80, 48, 14, 20, 11,  2, 34, 68, 14, 66]])

In [59]:
sorted = np.sort(v)
sorted

array([[23, 25, 45, 47, 57, 59, 76, 85, 89, 93],
       [ 2, 18, 18, 34, 40, 42, 50, 71, 91, 92],
       [ 7, 13, 23, 57, 69, 80, 83, 87, 90, 99],
       [ 1,  5, 12, 22, 52, 54, 58, 59, 68, 96],
       [25, 34, 37, 44, 46, 58, 78, 79, 93, 94],
       [ 0, 36, 44, 55, 61, 68, 79, 84, 88, 97],
       [ 2,  2, 20, 26, 30, 36, 79, 87, 92, 98],
       [ 4,  7, 31, 39, 45, 45, 48, 68, 68, 92],
       [30, 36, 43, 50, 53, 69, 73, 75, 87, 90],
       [ 8, 11, 30, 34, 39, 48, 61, 74, 84, 90],
       [18, 23, 31, 34, 44, 56, 56, 65, 76, 83],
       [ 6, 18, 36, 42, 43, 59, 72, 73, 89, 91],
       [ 3,  3, 18, 23, 67, 75, 80, 80, 83, 87],
       [ 8, 21, 28, 30, 42, 42, 55, 81, 91, 94],
       [11, 13, 16, 18, 21, 39, 40, 52, 95, 96],
       [ 1, 38, 46, 51, 51, 53, 55, 66, 78, 98],
       [ 2,  5, 45, 54, 68, 68, 71, 93, 96, 97],
       [25, 32, 35, 37, 38, 56, 61, 64, 69, 76],
       [ 8, 20, 42, 44, 47, 57, 62, 68, 75, 98],
       [ 2, 11, 14, 14, 20, 34, 48, 66, 68, 80]])

In [60]:
sorted = np.sort(v, axis = 0)
sorted

array([[ 2,  2,  6,  8,  1,  2,  1, 18,  0,  2],
       [ 2, 18, 13, 11, 11,  3, 11, 23,  4,  8],
       [ 3, 23, 13, 20, 18,  5, 18, 30,  5, 35],
       [ 7, 25, 14, 21, 36, 16, 25, 30,  8, 40],
       [ 7, 36, 18, 22, 37, 18, 30, 31, 14, 42],
       [12, 39, 20, 26, 45, 20, 34, 36, 32, 44],
       [21, 42, 25, 30, 47, 28, 36, 39, 39, 44],
       [23, 42, 34, 34, 48, 31, 38, 52, 40, 45],
       [23, 43, 38, 37, 53, 34, 45, 55, 50, 48],
       [34, 48, 44, 44, 68, 42, 58, 59, 51, 51],
       [42, 56, 45, 46, 78, 43, 59, 61, 56, 54],
       [61, 66, 50, 47, 79, 46, 62, 68, 57, 66],
       [61, 68, 53, 52, 80, 55, 71, 68, 57, 71],
       [64, 68, 55, 54, 83, 56, 75, 75, 57, 73],
       [73, 68, 58, 67, 83, 68, 79, 80, 59, 80],
       [78, 69, 65, 69, 84, 74, 81, 92, 72, 87],
       [80, 75, 68, 76, 94, 76, 83, 94, 87, 88],
       [90, 76, 69, 87, 95, 84, 85, 96, 91, 89],
       [93, 90, 79, 89, 96, 98, 87, 96, 92, 90],
       [98, 93, 97, 92, 97, 99, 91, 98, 93, 91]])

In [61]:
import numpy as np

In [62]:
# indexing

x = np.array([23, 45, 100, 0, -2])

In [63]:
x0 = x[0]
x0

23

In [64]:
x3 = x[2]
x3

100

In [65]:
xl = x[-1]
xl

-2

In [66]:
x

array([ 23,  45, 100,   0,  -2])

In [67]:
x[0] = 1000
x

array([1000,   45,  100,    0,   -2])

In [68]:

x = np.random.randint(10, size = (4, 4))
x

array([[6, 5, 4, 5],
       [0, 8, 2, 6],
       [9, 0, 7, 2],
       [7, 2, 7, 5]])

In [69]:
x[0][0]

6

In [70]:
x[1][2]

2

In [71]:
x[1][2] = 99

In [72]:
x[1][2]

99

In [73]:
x

array([[ 6,  5,  4,  5],
       [ 0,  8, 99,  6],
       [ 9,  0,  7,  2],
       [ 7,  2,  7,  5]])

In [74]:
# slicing

In [75]:
x = np.array([1, 4, 5, 9, 2, 12])
x

array([ 1,  4,  5,  9,  2, 12])

In [76]:
x[:3]

array([1, 4, 5])

In [77]:
x[4:]

array([ 2, 12])

In [78]:
x[0::2]

array([1, 5, 2])

In [79]:
x[::]

array([ 1,  4,  5,  9,  2, 12])

In [80]:
x = np.random.randint(10, size = (5, 5))
x

array([[4, 0, 0, 2, 0],
       [2, 9, 4, 3, 9],
       [1, 8, 4, 8, 6],
       [2, 6, 9, 4, 8],
       [8, 7, 5, 7, 5]])

In [81]:
x[:, 0]

array([4, 2, 1, 2, 8])

In [82]:
x[:, 1]

array([0, 9, 8, 6, 7])

In [83]:
x[0, :]

array([4, 0, 0, 2, 0])

In [84]:
x[0]

array([4, 0, 0, 2, 0])

In [85]:
x[0:2, 0:2]

array([[4, 0],
       [2, 9]])

In [86]:
x[0:4, :]

array([[4, 0, 0, 2, 0],
       [2, 9, 4, 3, 9],
       [1, 8, 4, 8, 6],
       [2, 6, 9, 4, 8]])

In [87]:
x[0:4, 2:]

array([[0, 2, 0],
       [4, 3, 9],
       [4, 8, 6],
       [9, 4, 8]])

In [88]:
x

array([[4, 0, 0, 2, 0],
       [2, 9, 4, 3, 9],
       [1, 8, 4, 8, 6],
       [2, 6, 9, 4, 8],
       [8, 7, 5, 7, 5]])

In [89]:
y = x[0:2, 0:3].copy()
y

array([[4, 0, 0],
       [2, 9, 4]])

In [90]:
# fancy

In [91]:
import numpy as np
x = np.arange(0,44, 4)
x

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [92]:
x[4]

16

In [93]:
[x[2], x[7]]

[8, 28]

In [94]:
take_it = [2, 6, 9]
x


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [95]:
x[take_it]

array([ 8, 24, 36])

In [96]:
x = np.arange(0,9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
row = np.array([0,1])
col = np.array([1,2])


In [98]:
x[row, col]

array([1, 5])

In [99]:
x[0, [col]]

array([[1, 2]])

In [100]:
# condition

In [101]:
x = np.array([29, -34, 45, 234, -9, 0])
x

array([ 29, -34,  45, 234,  -9,   0])

In [102]:
x > 28

array([ True, False,  True,  True, False, False])

In [103]:
x >= 0

array([ True, False,  True,  True, False,  True])

In [104]:
# maths

In [105]:
 x ** 2

array([  841,  1156,  2025, 54756,    81,     0])

In [106]:
x + 16

array([ 45, -18,  61, 250,   7,  16])

In [107]:
x // 2

array([ 14, -17,  22, 117,  -5,   0])

In [108]:
x - 100

array([ -71, -134,  -55,  134, -109, -100])

In [109]:
x


array([ 29, -34,  45, 234,  -9,   0])

In [110]:
np.subtract(x, 2)

array([ 27, -36,  43, 232, -11,  -2])

In [111]:
np.add(x, 100)

array([129,  66, 145, 334,  91, 100])

In [112]:
np.multiply(x , 10)

array([ 290, -340,  450, 2340,  -90,    0])

In [113]:
np.divide(x, 2)

array([ 14.5, -17. ,  22.5, 117. ,  -4.5,   0. ])

In [114]:
np.power(x, 2)

array([  841,  1156,  2025, 54756,    81,     0])

In [115]:
x

array([ 29, -34,  45, 234,  -9,   0])

In [116]:
x % 2 

array([1, 0, 1, 0, 1, 0])

In [117]:
np.mod(x, 2)

array([1, 0, 1, 0, 1, 0])

In [118]:
np.absolute(np.array([-9]))

array([9])

In [119]:
np.sin(180)

-0.8011526357338304

In [120]:
np.log10(10)

1.0