# Numpy

In [1]:
x = [1, 3, 5]
y = [7, 4, 0]
x

[1, 3, 5]

In [2]:
y

[7, 4, 0]

In [3]:
import numpy as np

In [4]:
# x = [1, 3, 5]
# y = [7, 4, 0]

x = np.array(x)
y = np.array(y)


In [5]:
 x * y

array([ 7, 12,  0])

In [6]:
2 * x - y

array([-5,  2, 10])

In [7]:
np.array([100, 80, 40])

array([100,  80,  40])

In [8]:
k = np.array([34, 23, 89])
type(k)

numpy.ndarray

In [9]:
np.array([2.3, 5, 6.9, 10], dtype = "int")

array([ 2,  5,  6, 10])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((4,4), dtype = "int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
np.full((3,3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [14]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [16]:
np.random.normal(10, 1, (2,2))  # ort - sapma - size

array([[ 9.20546184, 11.13505242],
       [ 9.3508537 , 10.29664899]])

In [17]:
np.random.randint(0, 10, (2,2))

array([[8, 3],
       [3, 9]])

In [18]:
# attr

# ndim: Number of array dimensions, shape: array dimensions, size: Number of elements in the array, dtype: data type

In [19]:
a = np.random.randint(10, size = 10)

In [20]:
a.ndim

1

In [21]:
a.shape

(10,)

In [22]:
a.size

10

In [23]:
a.dtype

dtype('int64')

In [24]:
b = np.random.randint(10, size = (4, 4))
b

array([[9, 3, 8, 7],
       [2, 3, 6, 5],
       [7, 5, 6, 2],
       [2, 2, 6, 9]])

In [25]:
b.shape

(4, 4)

In [26]:
b.size

16

In [27]:
b.ndim

2

In [28]:
b.dtype

dtype('int64')