# Numpy

In [1]:
x = [1, 3, 5]
y = [7, 4, 0]
x

[1, 3, 5]

In [2]:
y

[7, 4, 0]

In [3]:
import numpy as np

In [4]:
# x = [1, 3, 5]
# y = [7, 4, 0]

x = np.array(x)
y = np.array(y)


In [5]:
 x * y

array([ 7, 12,  0])

In [6]:
2 * x - y

array([-5,  2, 10])

In [7]:
np.array([100, 80, 40])

array([100,  80,  40])

In [8]:
k = np.array([34, 23, 89])
type(k)

numpy.ndarray

In [9]:
np.array([2.3, 5, 6.9, 10], dtype = "int")

array([ 2,  5,  6, 10])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((4,4), dtype = "int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
np.full((3,3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [14]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [16]:
np.random.normal(10, 1, (2,2))  # ort - sapma - size

array([[8.21955863, 9.21712966],
       [9.46434805, 9.34182893]])

In [17]:
np.random.randint(0, 10, (2,2))

array([[8, 9],
       [2, 2]])

In [18]:
# attr

# ndim: Number of array dimensions, shape: array dimensions, size: Number of elements in the array, dtype: data type

In [19]:
a = np.random.randint(10, size = 10)

In [20]:
a.ndim

1

In [21]:
a.shape

(10,)

In [22]:
a.size

10

In [23]:
a.dtype

dtype('int64')

In [24]:
b = np.random.randint(10, size = (4, 4))
b

array([[6, 6, 4, 9],
       [3, 7, 1, 8],
       [5, 9, 2, 9],
       [2, 5, 8, 6]])

In [25]:
b.shape

(4, 4)

In [26]:
b.size

16

In [27]:
b.ndim

2

In [28]:
b.dtype

dtype('int64')

In [29]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# reshape
np.arange(0,10).reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x.ndim

1

In [33]:
y = x.reshape((3,3))
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
y.ndim

2

In [35]:
# concatenate
x = np.array([3, 4, 2])
y = np.array([2, 6, 8])

In [36]:
np.concatenate([x,y])

array([3, 4, 2, 2, 6, 8])

In [37]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate([x, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate([x, x], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [40]:
# split

In [41]:
x = np.array([23, 45, 56, 67, 45, 12, 34])
x

array([23, 45, 56, 67, 45, 12, 34])

In [42]:
np.split(x, [2, 3, 5])

[array([23, 45]), array([56]), array([67, 45]), array([12, 34])]

In [43]:
a, b, c, d = np.split(x, [2, 3, 5])

In [44]:
a

array([23, 45])

In [45]:
d

array([12, 34])

In [46]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
np.vsplit(x, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [48]:
up, low = np.vsplit(x, [3])
up

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
low

array([[12, 13, 14, 15]])

In [50]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
np.hsplit(x, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [52]:
# sorting

In [53]:
x = np.array([223, 566, 421, 100])
x

array([223, 566, 421, 100])

In [54]:
k = np.sort(x)
k

array([100, 223, 421, 566])

In [55]:
x

array([223, 566, 421, 100])

In [56]:
x.sort()

In [57]:
x

array([100, 223, 421, 566])

In [58]:
v = np.random.randint(0,100, (20,10))
v


array([[12, 88, 32, 37, 78,  8, 28, 37, 60, 93],
       [23, 49, 21, 87, 56, 35, 40, 65, 26, 30],
       [62, 57, 85, 65, 18, 48, 17, 25, 32, 78],
       [84,  9, 63,  1, 13, 48, 84,  5, 42, 55],
       [47, 53, 44, 75, 41, 28,  6, 14, 61, 18],
       [16, 48, 56, 16, 47,  8, 93, 57, 21, 99],
       [96, 51, 35, 67, 25, 54,  7, 36, 30, 35],
       [45, 77, 92, 40, 49, 88, 40,  0,  5, 34],
       [ 1, 98, 84, 26, 40, 31, 56, 81, 20, 84],
       [96, 93, 15, 69, 46, 29, 78, 40, 13, 72],
       [94, 93,  8, 41, 13, 71, 54, 43, 60, 34],
       [44, 84,  0, 63, 10, 76, 70,  3, 30, 72],
       [75, 30, 67, 75, 90, 17, 52, 91,  7,  1],
       [65, 56, 49, 28, 39, 29,  7, 40, 51, 69],
       [ 6, 42,  9, 27, 56, 56, 91, 56, 51, 77],
       [39, 21,  4, 23, 26,  2, 52, 82, 48, 21],
       [22, 22, 47, 94, 30, 10, 69, 14, 59, 76],
       [51, 25, 53, 62, 49, 18, 99, 58,  1, 47],
       [28, 10, 22, 89, 77,  6, 74, 68, 96, 60],
       [65, 27, 87, 46, 73, 71, 89, 25, 43, 14]])

In [59]:
sorted = np.sort(v)
sorted

array([[ 8, 12, 28, 32, 37, 37, 60, 78, 88, 93],
       [21, 23, 26, 30, 35, 40, 49, 56, 65, 87],
       [17, 18, 25, 32, 48, 57, 62, 65, 78, 85],
       [ 1,  5,  9, 13, 42, 48, 55, 63, 84, 84],
       [ 6, 14, 18, 28, 41, 44, 47, 53, 61, 75],
       [ 8, 16, 16, 21, 47, 48, 56, 57, 93, 99],
       [ 7, 25, 30, 35, 35, 36, 51, 54, 67, 96],
       [ 0,  5, 34, 40, 40, 45, 49, 77, 88, 92],
       [ 1, 20, 26, 31, 40, 56, 81, 84, 84, 98],
       [13, 15, 29, 40, 46, 69, 72, 78, 93, 96],
       [ 8, 13, 34, 41, 43, 54, 60, 71, 93, 94],
       [ 0,  3, 10, 30, 44, 63, 70, 72, 76, 84],
       [ 1,  7, 17, 30, 52, 67, 75, 75, 90, 91],
       [ 7, 28, 29, 39, 40, 49, 51, 56, 65, 69],
       [ 6,  9, 27, 42, 51, 56, 56, 56, 77, 91],
       [ 2,  4, 21, 21, 23, 26, 39, 48, 52, 82],
       [10, 14, 22, 22, 30, 47, 59, 69, 76, 94],
       [ 1, 18, 25, 47, 49, 51, 53, 58, 62, 99],
       [ 6, 10, 22, 28, 60, 68, 74, 77, 89, 96],
       [14, 25, 27, 43, 46, 65, 71, 73, 87, 89]])

In [60]:
sorted = np.sort(v, axis = 0)
sorted

array([[ 1,  9,  0,  1, 10,  2,  6,  0,  1,  1],
       [ 6, 10,  4, 16, 13,  6,  7,  3,  5, 14],
       [12, 21,  8, 23, 13,  8,  7,  5,  7, 18],
       [16, 22,  9, 26, 18,  8, 17, 14, 13, 21],
       [22, 25, 15, 27, 25, 10, 28, 14, 20, 30],
       [23, 27, 21, 28, 26, 17, 40, 25, 21, 34],
       [28, 30, 22, 37, 30, 18, 40, 25, 26, 34],
       [39, 42, 32, 40, 39, 28, 52, 36, 30, 35],
       [44, 48, 35, 41, 40, 29, 52, 37, 30, 47],
       [45, 49, 44, 46, 41, 29, 54, 40, 32, 55],
       [47, 51, 47, 62, 46, 31, 56, 40, 42, 60],
       [51, 53, 49, 63, 47, 35, 69, 43, 43, 69],
       [62, 56, 53, 65, 49, 48, 70, 56, 48, 72],
       [65, 57, 56, 67, 49, 48, 74, 57, 51, 72],
       [65, 77, 63, 69, 56, 54, 78, 58, 51, 76],
       [75, 84, 67, 75, 56, 56, 84, 65, 59, 77],
       [84, 88, 84, 75, 73, 71, 89, 68, 60, 78],
       [94, 93, 85, 87, 77, 71, 91, 81, 60, 84],
       [96, 93, 87, 89, 78, 76, 93, 82, 61, 93],
       [96, 98, 92, 94, 90, 88, 99, 91, 96, 99]])