# Numpy

In [1]:
x = [1, 3, 5]
y = [7, 4, 0]
x

[1, 3, 5]

In [2]:
y

[7, 4, 0]

In [3]:
import numpy as np

In [4]:
# x = [1, 3, 5]
# y = [7, 4, 0]

x = np.array(x)
y = np.array(y)


In [5]:
 x * y

array([ 7, 12,  0])

In [6]:
2 * x - y

array([-5,  2, 10])

In [7]:
np.array([100, 80, 40])

array([100,  80,  40])

In [8]:
k = np.array([34, 23, 89])
type(k)

numpy.ndarray

In [9]:
np.array([2.3, 5, 6.9, 10], dtype = "int")

array([ 2,  5,  6, 10])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((4,4), dtype = "int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
np.full((3,3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [14]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [16]:
np.random.normal(10, 1, (2,2))  # ort - sapma - size

array([[ 9.18592538,  9.63636895],
       [11.1578149 ,  8.80525089]])

In [17]:
np.random.randint(0, 10, (2,2))

array([[9, 6],
       [8, 9]])

In [18]:
# attr

# ndim: Number of array dimensions, shape: array dimensions, size: Number of elements in the array, dtype: data type

In [19]:
a = np.random.randint(10, size = 10)

In [20]:
a.ndim

1

In [21]:
a.shape

(10,)

In [22]:
a.size

10

In [23]:
a.dtype

dtype('int64')

In [24]:
b = np.random.randint(10, size = (4, 4))
b

array([[5, 1, 3, 5],
       [4, 1, 9, 9],
       [9, 2, 1, 2],
       [0, 9, 3, 6]])

In [25]:
b.shape

(4, 4)

In [26]:
b.size

16

In [27]:
b.ndim

2

In [28]:
b.dtype

dtype('int64')

In [29]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# reshape
np.arange(0,10).reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x.ndim

1

In [33]:
y = x.reshape((3,3))
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
y.ndim

2

In [35]:
# concatenate
x = np.array([3, 4, 2])
y = np.array([2, 6, 8])

In [36]:
np.concatenate([x,y])

array([3, 4, 2, 2, 6, 8])

In [37]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate([x, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate([x, x], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [40]:
# split

In [41]:
x = np.array([23, 45, 56, 67, 45, 12, 34])
x

array([23, 45, 56, 67, 45, 12, 34])

In [42]:
np.split(x, [2, 3, 5])

[array([23, 45]), array([56]), array([67, 45]), array([12, 34])]

In [43]:
a, b, c, d = np.split(x, [2, 3, 5])

In [44]:
a

array([23, 45])

In [45]:
d

array([12, 34])

In [46]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
np.vsplit(x, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [48]:
up, low = np.vsplit(x, [3])
up

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
low

array([[12, 13, 14, 15]])

In [50]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
np.hsplit(x, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [52]:
# sorting

In [53]:
x = np.array([223, 566, 421, 100])
x

array([223, 566, 421, 100])

In [54]:
k = np.sort(x)
k

array([100, 223, 421, 566])

In [55]:
x

array([223, 566, 421, 100])

In [56]:
x.sort()

In [57]:
x

array([100, 223, 421, 566])

In [58]:
v = np.random.randint(0,100, (20,10))
v


array([[19, 21, 45,  9, 86, 73, 56, 50, 77,  0],
       [36, 19,  5,  4, 80, 36, 60, 64, 73, 83],
       [92, 46, 11, 19, 30, 37, 67, 26,  8, 32],
       [62, 36, 75, 34,  8, 73,  2, 51, 71, 91],
       [61, 65, 18, 74, 53, 58, 60, 82, 90, 64],
       [11, 80, 28, 63, 37, 92, 59, 62, 26, 95],
       [75, 38, 48, 12, 81, 87, 81, 98, 57, 53],
       [87, 86, 60,  7, 66, 95, 91, 59, 29,  9],
       [42, 27, 82, 11, 13, 49, 84, 81, 24, 95],
       [99, 23,  8, 15, 26, 53, 76, 66,  7, 35],
       [51, 94, 54, 16, 88, 42, 13, 41,  3, 29],
       [52, 15, 35, 17, 90, 83, 46, 12, 69, 48],
       [36, 42, 53, 95, 25, 78, 15,  7,  6, 40],
       [34, 72, 95,  9,  4, 73,  1, 15, 16,  4],
       [83, 66, 94, 59, 16, 50, 87, 64, 89, 45],
       [53, 69, 83, 20, 41, 26, 54, 81,  8, 88],
       [77, 77, 62, 87, 60, 35, 32, 17, 83,  7],
       [83, 74, 19, 80,  6, 34, 38, 64, 20, 97],
       [33, 93, 59, 10, 39, 27, 36, 60, 74, 43],
       [12, 53, 88, 45, 43, 78, 98, 90, 71, 29]])

In [59]:
sorted = np.sort(v)
sorted

array([[ 0,  9, 19, 21, 45, 50, 56, 73, 77, 86],
       [ 4,  5, 19, 36, 36, 60, 64, 73, 80, 83],
       [ 8, 11, 19, 26, 30, 32, 37, 46, 67, 92],
       [ 2,  8, 34, 36, 51, 62, 71, 73, 75, 91],
       [18, 53, 58, 60, 61, 64, 65, 74, 82, 90],
       [11, 26, 28, 37, 59, 62, 63, 80, 92, 95],
       [12, 38, 48, 53, 57, 75, 81, 81, 87, 98],
       [ 7,  9, 29, 59, 60, 66, 86, 87, 91, 95],
       [11, 13, 24, 27, 42, 49, 81, 82, 84, 95],
       [ 7,  8, 15, 23, 26, 35, 53, 66, 76, 99],
       [ 3, 13, 16, 29, 41, 42, 51, 54, 88, 94],
       [12, 15, 17, 35, 46, 48, 52, 69, 83, 90],
       [ 6,  7, 15, 25, 36, 40, 42, 53, 78, 95],
       [ 1,  4,  4,  9, 15, 16, 34, 72, 73, 95],
       [16, 45, 50, 59, 64, 66, 83, 87, 89, 94],
       [ 8, 20, 26, 41, 53, 54, 69, 81, 83, 88],
       [ 7, 17, 32, 35, 60, 62, 77, 77, 83, 87],
       [ 6, 19, 20, 34, 38, 64, 74, 80, 83, 97],
       [10, 27, 33, 36, 39, 43, 59, 60, 74, 93],
       [12, 29, 43, 45, 53, 71, 78, 88, 90, 98]])

In [60]:
sorted = np.sort(v, axis = 0)
sorted

array([[11, 15,  5,  4,  4, 26,  1,  7,  3,  0],
       [12, 19,  8,  7,  6, 27,  2, 12,  6,  4],
       [19, 21, 11,  9,  8, 34, 13, 15,  7,  7],
       [33, 23, 18,  9, 13, 35, 15, 17,  8,  9],
       [34, 27, 19, 10, 16, 36, 32, 26,  8, 29],
       [36, 36, 28, 11, 25, 37, 36, 41, 16, 29],
       [36, 38, 35, 12, 26, 42, 38, 50, 20, 32],
       [42, 42, 45, 15, 30, 49, 46, 51, 24, 35],
       [51, 46, 48, 16, 37, 50, 54, 59, 26, 40],
       [52, 53, 53, 17, 39, 53, 56, 60, 29, 43],
       [53, 65, 54, 19, 41, 58, 59, 62, 57, 45],
       [61, 66, 59, 20, 43, 73, 60, 64, 69, 48],
       [62, 69, 60, 34, 53, 73, 60, 64, 71, 53],
       [75, 72, 62, 45, 60, 73, 67, 64, 71, 64],
       [77, 74, 75, 59, 66, 78, 76, 66, 73, 83],
       [83, 77, 82, 63, 80, 78, 81, 81, 74, 88],
       [83, 80, 83, 74, 81, 83, 84, 81, 77, 91],
       [87, 86, 88, 80, 86, 87, 87, 82, 83, 95],
       [92, 93, 94, 87, 88, 92, 91, 90, 89, 95],
       [99, 94, 95, 95, 90, 95, 98, 98, 90, 97]])

In [61]:
import numpy as np

In [62]:
# indexing

x = np.array([23, 45, 100, 0, -2])

In [63]:
x0 = x[0]
x0

23

In [64]:
x3 = x[2]
x3

100

In [65]:
xl = x[-1]
xl

-2

In [66]:
x

array([ 23,  45, 100,   0,  -2])

In [67]:
x[0] = 1000
x

array([1000,   45,  100,    0,   -2])

In [68]:

x = np.random.randint(10, size = (4, 4))
x

array([[8, 2, 5, 5],
       [6, 1, 5, 6],
       [5, 4, 8, 1],
       [8, 3, 9, 9]])

In [69]:
x[0][0]

8

In [70]:
x[1][2]

5

In [71]:
x[1][2] = 99

In [72]:
x[1][2]

99

In [73]:
x

array([[ 8,  2,  5,  5],
       [ 6,  1, 99,  6],
       [ 5,  4,  8,  1],
       [ 8,  3,  9,  9]])

In [74]:
# slicing

In [75]:
x = np.array([1, 4, 5, 9, 2, 12])
x

array([ 1,  4,  5,  9,  2, 12])

In [76]:
x[:3]

array([1, 4, 5])

In [77]:
x[4:]

array([ 2, 12])

In [78]:
x[0::2]

array([1, 5, 2])

In [79]:
x[::]

array([ 1,  4,  5,  9,  2, 12])

In [80]:
x = np.random.randint(10, size = (5, 5))
x

array([[9, 7, 7, 3, 6],
       [9, 1, 5, 0, 8],
       [4, 8, 1, 6, 6],
       [2, 9, 4, 5, 0],
       [2, 2, 8, 1, 1]])

In [81]:
x[:, 0]

array([9, 9, 4, 2, 2])

In [82]:
x[:, 1]

array([7, 1, 8, 9, 2])

In [83]:
x[0, :]

array([9, 7, 7, 3, 6])

In [84]:
x[0]

array([9, 7, 7, 3, 6])

In [85]:
x[0:2, 0:2]

array([[9, 7],
       [9, 1]])

In [86]:
x[0:4, :]

array([[9, 7, 7, 3, 6],
       [9, 1, 5, 0, 8],
       [4, 8, 1, 6, 6],
       [2, 9, 4, 5, 0]])

In [87]:
x[0:4, 2:]

array([[7, 3, 6],
       [5, 0, 8],
       [1, 6, 6],
       [4, 5, 0]])

In [88]:
x

array([[9, 7, 7, 3, 6],
       [9, 1, 5, 0, 8],
       [4, 8, 1, 6, 6],
       [2, 9, 4, 5, 0],
       [2, 2, 8, 1, 1]])

In [89]:
y = x[0:2, 0:3].copy()
y

array([[9, 7, 7],
       [9, 1, 5]])