In [1]:
import pandas as pd

In [2]:
pd.Series([23, 45, -36, 12, 0, 100])

0     23
1     45
2    -36
3     12
4      0
5    100
dtype: int64

In [3]:
seri = pd.Series([23, 45, -36, 12, 0, 100])

type(seri)

pandas.core.series.Series

In [4]:
seri.axes

[RangeIndex(start=0, stop=6, step=1)]

In [5]:
seri.dtype

dtype('int64')

In [6]:
seri.ndim

1

In [7]:
seri.size

6

In [8]:
seri.values

array([ 23,  45, -36,  12,   0, 100])

In [9]:
seri.head()

0    23
1    45
2   -36
3    12
4     0
dtype: int64

In [10]:
seri.head(3)

0    23
1    45
2   -36
dtype: int64

In [11]:
seri.tail()

1     45
2    -36
3     12
4      0
5    100
dtype: int64

In [12]:
seri.tail(3)

3     12
4      0
5    100
dtype: int64

In [13]:
# index name

In [14]:
pd.Series([455, 354, 1332, 43553, 90, "string"], index = ["first",2,3,4,5,6])

first       455
2           354
3          1332
4         43553
5            90
6        string
dtype: object

In [15]:
seri = pd.Series([455, 354, 1332, 43553, 90, "string"], index = ["first",2,3,4,5,6])

In [16]:
seri["first"]

455

In [17]:
seri["first" : 5]

first      455
2          354
3         1332
4        43553
5           90
dtype: object

In [18]:
dict = pd.Series({"james" :10,
                 "elena" : 34,
                  "william": 29,
                  "mila": 22                 
                 })

In [19]:
dict

james      10
elena      34
william    29
mila       22
dtype: int64

In [20]:
dict["james" : "william"]

james      10
elena      34
william    29
dtype: int64

In [21]:
pd.concat([dict, seri])

james          10
elena          34
william        29
mila           22
first         455
2             354
3            1332
4           43553
5              90
6          string
dtype: object

In [22]:
import numpy as np

x = np.array([23, 42, 13, 90, 80, 68])

seri = pd.Series(x)

seri

0    23
1    42
2    13
3    90
4    80
5    68
dtype: int64

In [23]:
seri[0:4]

0    23
1    42
2    13
3    90
dtype: int64

In [24]:
seri[4:]

4    80
5    68
dtype: int64

In [25]:
seri.keys

<bound method Series.keys of 0    23
1    42
2    13
3    90
4    80
5    68
dtype: int64>

In [26]:
seri.index

RangeIndex(start=0, stop=6, step=1)

In [27]:
list(seri.items())

[(0, 23), (1, 42), (2, 13), (3, 90), (4, 80), (5, 68)]

In [28]:
seri.values

array([23, 42, 13, 90, 80, 68])

In [29]:
seri

0    23
1    42
2    13
3    90
4    80
5    68
dtype: int64

In [30]:
4 in seri 

True

In [31]:
42 in seri

False

In [32]:

l = [20, 43, 12, 98, 36]
l

[20, 43, 12, 98, 36]

In [33]:
pd.DataFrame(l, columns = ["col name"])

col name
0        20
1        43
2        12
3        98
4        36

In [34]:
import numpy as np

In [35]:
k1 = np.random.randint(10, size = 5)
k2 = np.random.randint(10, size = 5)
k3 = np.random.randint(10, size = 5)
k1

array([6, 0, 7, 2, 3])

In [36]:
dict = {"var1":k1,
        "var2":k2,
        "var3":k3
       }

dict

{'var1': array([6, 0, 7, 2, 3]),
 'var2': array([1, 4, 2, 8, 7]),
 'var3': array([1, 5, 0, 6, 3])}

In [37]:
import pandas as pd

In [38]:
df = pd.DataFrame(dict)
df

var1  var2  var3
0     6     1     1
1     0     4     5
2     7     2     0
3     2     8     6
4     3     7     3

In [39]:
df[0:1]

var1  var2  var3
0     6     1     1

In [40]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [41]:
df.index = ["x", "y", "z", "q", "w"]

In [42]:
df.index

Index(['x', 'y', 'z', 'q', 'w'], dtype='object')

In [43]:
df

var1  var2  var3
x     6     1     1
y     0     4     5
z     7     2     0
q     2     8     6
w     3     7     3

In [44]:
df[
    "y" : "q"
]

var1  var2  var3
y     0     4     5
z     7     2     0
q     2     8     6

In [45]:
df

var1  var2  var3
x     6     1     1
y     0     4     5
z     7     2     0
q     2     8     6
w     3     7     3

In [46]:
df.drop("x")

var1  var2  var3
y     0     4     5
z     7     2     0
q     2     8     6
w     3     7     3

In [47]:
df

var1  var2  var3
x     6     1     1
y     0     4     5
z     7     2     0
q     2     8     6
w     3     7     3

In [48]:
df.drop("x", inplace= True)

In [49]:
df

var1  var2  var3
y     0     4     5
z     7     2     0
q     2     8     6
w     3     7     3

In [50]:
l = ["w"]

In [51]:
# fancy

In [52]:
df.drop(l)

var1  var2  var3
y     0     4     5
z     7     2     0
q     2     8     6

In [53]:
"var1" in df

True

In [54]:
l = ["var4", "var2", "var9"]

In [55]:
df

var1  var2  var3
y     0     4     5
z     7     2     0
q     2     8     6
w     3     7     3

In [56]:
for i in l:
    print(i in df)

False
True
False


In [57]:
df

var1  var2  var3
y     0     4     5
z     7     2     0
q     2     8     6
w     3     7     3

In [58]:
df["var4"] = df["var1"] + df["var2"]

In [59]:
df

var1  var2  var3  var4
y     0     4     5     4
z     7     2     0     9
q     2     8     6    10
w     3     7     3    10

In [60]:
df.drop("var4", axis = 1, inplace = True)

In [61]:
df

var1  var2  var3
y     0     4     5
z     7     2     0
q     2     8     6
w     3     7     3

In [62]:
l = ["var1"]

In [63]:
df.drop(l, axis = 1)

var2  var3
y     4     5
z     2     0
q     8     6
w     7     3

In [64]:
df

var1  var2  var3
y     0     4     5
z     7     2     0
q     2     8     6
w     3     7     3

In [65]:
# loc & iloc

In [66]:
import numpy as np
import pandas as pd

In [67]:
x = np.random.randint(1, 30 , size = (10, 3)) 

In [68]:
df = pd.DataFrame(x, columns = ["var1", "var2", "var3"])
df

var1  var2  var3
0    29    24    29
1    14    23     5
2    27    19    13
3    28    20    25
4    25    21    17
5    11    14     2
6    25    17     5
7    18     7    29
8     8    18    25
9     7    11    11

In [69]:
df.loc[0:3]

var1  var2  var3
0    29    24    29
1    14    23     5
2    27    19    13
3    28    20    25

In [70]:
df.iloc[0:3]

var1  var2  var3
0    29    24    29
1    14    23     5
2    27    19    13

In [71]:
df

var1  var2  var3
0    29    24    29
1    14    23     5
2    27    19    13
3    28    20    25
4    25    21    17
5    11    14     2
6    25    17     5
7    18     7    29
8     8    18    25
9     7    11    11

In [72]:
df.iloc[:3, :2]

var1  var2
0    29    24
1    14    23
2    27    19

In [73]:
df.loc[:3, "var1"]

0    29
1    14
2    27
3    28
Name: var1, dtype: int64

In [74]:
df.loc[:3, "var1"] # use loc for str or below

0    29
1    14
2    27
3    28
Name: var1, dtype: int64

In [75]:
df.iloc[0:3] ["var2"]

0    24
1    23
2    19
Name: var2, dtype: int64

In [76]:
x = np.random.randint(1, 30 , size = (10, 3)) 
df = pd.DataFrame(x, columns = ["var1", "var2", "var3"])
df

var1  var2  var3
0    13    18    22
1     6    19    27
2    24    23     8
3     6     4     8
4    29     3     9
5    21     3     6
6    20     8     1
7    29    14    26
8    28    27    29
9    22     3    29

In [77]:
df[0:4][["var1", "var2"]]

var1  var2
0    13    18
1     6    19
2    24    23
3     6     4

In [78]:
df


var1  var2  var3
0    13    18    22
1     6    19    27
2    24    23     8
3     6     4     8
4    29     3     9
5    21     3     6
6    20     8     1
7    29    14    26
8    28    27    29
9    22     3    29

In [79]:
df.var1

0    13
1     6
2    24
3     6
4    29
5    21
6    20
7    29
8    28
9    22
Name: var1, dtype: int64

In [80]:
df[df.var1 > 20]

var1  var2  var3
2    24    23     8
4    29     3     9
5    21     3     6
7    29    14    26
8    28    27    29
9    22     3    29

In [81]:
df[(df.var1 > 20) & (df.var3 < 30)] 

var1  var2  var3
2    24    23     8
4    29     3     9
5    21     3     6
7    29    14    26
8    28    27    29
9    22     3    29

In [82]:
import pandas as pd

In [83]:
df1 = pd.DataFrame({"workers": ["Tamer", "Mert", "Eda", "Buse"],
                    "group" : ["Engineering", "HR", "Accounting", "Product"]               
                   })
df1

workers        group
0   Tamer  Engineering
1    Mert           HR
2     Eda   Accounting
3    Buse      Product

In [84]:
df2 = pd.DataFrame({"workers": ["Tamer", "Mert", "Eda", "Buse"],
                    "date" : ["2020", "2000", "2010", "2008"]               
                   })
df2

workers  date
0   Tamer  2020
1    Mert  2000
2     Eda  2010
3    Buse  2008

In [85]:
pd.merge(df1, df2)

workers        group  date
0   Tamer  Engineering  2020
1    Mert           HR  2000
2     Eda   Accounting  2010
3    Buse      Product  2008

In [86]:
# aggregation & grouping

In [87]:
import seaborn as sns

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [88]:
?sns.load_dataset

In [89]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [90]:
df.shape

(1035, 6)

In [91]:
df.mean()

/tmp/ipykernel_20/3698961737.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [92]:
df["mass"].mean()

2.6381605847953216

In [93]:
df["mass"].count()

513

In [94]:
df["mass"].min()

0.0036

In [95]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [96]:
df.dropna().describe().T  # for nan val

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0