In [1]:
import pandas as pd

In [2]:
pd.Series([23, 45, -36, 12, 0, 100])

0     23
1     45
2    -36
3     12
4      0
5    100
dtype: int64

In [3]:
seri = pd.Series([23, 45, -36, 12, 0, 100])

type(seri)

pandas.core.series.Series

In [4]:
seri.axes

[RangeIndex(start=0, stop=6, step=1)]

In [5]:
seri.dtype

dtype('int64')

In [6]:
seri.ndim

1

In [7]:
seri.size

6

In [8]:
seri.values

array([ 23,  45, -36,  12,   0, 100])

In [9]:
seri.head()

0    23
1    45
2   -36
3    12
4     0
dtype: int64

In [10]:
seri.head(3)

0    23
1    45
2   -36
dtype: int64

In [11]:
seri.tail()

1     45
2    -36
3     12
4      0
5    100
dtype: int64

In [12]:
seri.tail(3)

3     12
4      0
5    100
dtype: int64

In [13]:
# index name

In [14]:
pd.Series([455, 354, 1332, 43553, 90, "string"], index = ["first",2,3,4,5,6])

first       455
2           354
3          1332
4         43553
5            90
6        string
dtype: object

In [15]:
seri = pd.Series([455, 354, 1332, 43553, 90, "string"], index = ["first",2,3,4,5,6])

In [16]:
seri["first"]

455

In [17]:
seri["first" : 5]

first      455
2          354
3         1332
4        43553
5           90
dtype: object

In [18]:
dict = pd.Series({"james" :10,
                 "elena" : 34,
                  "william": 29,
                  "mila": 22                 
                 })

In [19]:
dict

james      10
elena      34
william    29
mila       22
dtype: int64

In [20]:
dict["james" : "william"]

james      10
elena      34
william    29
dtype: int64

In [21]:
pd.concat([dict, seri])

james          10
elena          34
william        29
mila           22
first         455
2             354
3            1332
4           43553
5              90
6          string
dtype: object

In [22]:
import numpy as np

x = np.array([23, 42, 13, 90, 80, 68])

seri = pd.Series(x)

seri

0    23
1    42
2    13
3    90
4    80
5    68
dtype: int64

In [23]:
seri[0:4]

0    23
1    42
2    13
3    90
dtype: int64

In [24]:
seri[4:]

4    80
5    68
dtype: int64

In [25]:
seri.keys

<bound method Series.keys of 0    23
1    42
2    13
3    90
4    80
5    68
dtype: int64>

In [26]:
seri.index

RangeIndex(start=0, stop=6, step=1)

In [27]:
list(seri.items())

[(0, 23), (1, 42), (2, 13), (3, 90), (4, 80), (5, 68)]

In [28]:
seri.values

array([23, 42, 13, 90, 80, 68])

In [29]:
seri

0    23
1    42
2    13
3    90
4    80
5    68
dtype: int64

In [30]:
4 in seri 

True

In [31]:
42 in seri

False

In [32]:

l = [20, 43, 12, 98, 36]
l

[20, 43, 12, 98, 36]

In [33]:
pd.DataFrame(l, columns = ["col name"])

col name
0        20
1        43
2        12
3        98
4        36

In [34]:
import numpy as np

In [35]:
k1 = np.random.randint(10, size = 5)
k2 = np.random.randint(10, size = 5)
k3 = np.random.randint(10, size = 5)
k1

array([2, 3, 1, 0, 2])

In [36]:
dict = {"var1":k1,
        "var2":k2,
        "var3":k3
       }

dict

{'var1': array([2, 3, 1, 0, 2]),
 'var2': array([0, 1, 6, 2, 8]),
 'var3': array([1, 2, 6, 6, 6])}

In [37]:
import pandas as pd

In [38]:
df = pd.DataFrame(dict)
df

var1  var2  var3
0     2     0     1
1     3     1     2
2     1     6     6
3     0     2     6
4     2     8     6

In [39]:
df[0:1]

var1  var2  var3
0     2     0     1

In [40]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [41]:
df.index = ["x", "y", "z", "q", "w"]

In [42]:
df.index

Index(['x', 'y', 'z', 'q', 'w'], dtype='object')

In [43]:
df

var1  var2  var3
x     2     0     1
y     3     1     2
z     1     6     6
q     0     2     6
w     2     8     6

In [44]:
df[
    "y" : "q"
]

var1  var2  var3
y     3     1     2
z     1     6     6
q     0     2     6

In [45]:
df

var1  var2  var3
x     2     0     1
y     3     1     2
z     1     6     6
q     0     2     6
w     2     8     6

In [46]:
df.drop("x")

var1  var2  var3
y     3     1     2
z     1     6     6
q     0     2     6
w     2     8     6

In [47]:
df

var1  var2  var3
x     2     0     1
y     3     1     2
z     1     6     6
q     0     2     6
w     2     8     6

In [48]:
df.drop("x", inplace= True)

In [49]:
df

var1  var2  var3
y     3     1     2
z     1     6     6
q     0     2     6
w     2     8     6

In [50]:
l = ["w"]

In [51]:
# fancy

In [52]:
df.drop(l)

var1  var2  var3
y     3     1     2
z     1     6     6
q     0     2     6

In [53]:
"var1" in df

True

In [54]:
l = ["var4", "var2", "var9"]

In [55]:
df

var1  var2  var3
y     3     1     2
z     1     6     6
q     0     2     6
w     2     8     6

In [56]:
for i in l:
    print(i in df)

False
True
False


In [57]:
df

var1  var2  var3
y     3     1     2
z     1     6     6
q     0     2     6
w     2     8     6

In [58]:
df["var4"] = df["var1"] + df["var2"]

In [59]:
df

var1  var2  var3  var4
y     3     1     2     4
z     1     6     6     7
q     0     2     6     2
w     2     8     6    10

In [60]:
df.drop("var4", axis = 1, inplace = True)

In [61]:
df

var1  var2  var3
y     3     1     2
z     1     6     6
q     0     2     6
w     2     8     6

In [62]:
l = ["var1"]

In [63]:
df.drop(l, axis = 1)

var2  var3
y     1     2
z     6     6
q     2     6
w     8     6

In [64]:
df

var1  var2  var3
y     3     1     2
z     1     6     6
q     0     2     6
w     2     8     6